"""Renders the profile JSON into `loadgen/src/market_flow/polymarket_profile.rs`.

A pure formatter: every number is in the JSON already, so the same JSON always gives the same
bytes. The layout is rustfmt's for this repo (max_width 110), so `./dev fmt` leaves the file as
it is: a literal that fits on its line stays on it, a longer struct takes one field per line,
and a long array of numbers fills its lines. The types are in
`loadgen/src/market_flow/profile.rs`.
"""

MAX_WIDTH = 110

HEADER = """\
//! Polymarket Perps' flow profile, as recorded on 2026-09-30 (`docs/DECISIONS.md` D-034): the
//! 88 real markets and the distributions of [`POLYMARKET`]. Types, units and invariants:
//! `profile.rs`.
//!
//! GENERATED by `python3 tools/calibrate/calibrate.py generate` from
//! `tools/calibrate/profile-2026-09-30.json`: do not edit, change the tool and regenerate. The
//! JSON was derived by `python3 tools/calibrate/calibrate.py extract` from the recorded sample
//! (`data/`, never committed: 2026-09-29 14:00 to 2026-09-30 15:59 UTC, and the instruments of
//! 2026-09-30) and from the calibration outputs copied into `tools/calibrate/inputs/`. It holds
//! derived parameters only. To verify this file: `python3 tools/calibrate/calibrate.py generate
//! --check` (`tools/calibrate/README.md`).
"""

# The types the file names, in rustfmt's order.
TYPES = [
    "Ar1", "BookClass", "BookShape", "BurstModel", "Gaps", "Jumps", "LevelSizes", "LeverageClass",
    "LogComponent", "MakerActivity", "Market", "MoveModel", "PointMass", "Profile", "Shocks", "Spread",
    "Table", "TakerNotional", "Takers", "Tier",
]

BOOK_CLASS = {
    "majors": "Majors",
    "alt_crypto": "AltCrypto",
    "longtail_crypto": "LongTailCrypto",
    "tradfi_equities": "TradfiEquities",
    "tradfi_macro": "TradfiMacro",
}
LEVERAGE_CLASS = {"L50": "Max50", "L20": "Max20", "L10": "Max10", "L3-5": "Max3To5"}
MOVES_STATIC = {"L50": "MOVES_50X", "L20": "MOVES_20X", "L10": "MOVES_10X", "L3-5": "MOVES_3X_5X"}
GAP_BUCKETS = ["1_4", "5_9", "10_19"]


def ident(name):
    """A static's name: `alt_crypto` -> `ALT_CRYPTO`, `WTIOIL-USD` -> `WTIOIL`."""
    if name.endswith("-USD"):
        name = name[: -len("-USD")]
    return "".join(c if c.isalnum() else "_" for c in name.upper())


def spread_static(name):
    return "ONE_TICK" if name == "one_tick" else ident(name) + "_SPREAD"


def number(n):
    """An integer as the repo writes one: digits grouped by thousands from 1,000 up (4_096)."""
    text, groups = str(abs(n)), []
    while len(text) > 3:
        groups.insert(0, text[-3:])
        text = text[:-3]
    return ("-" if n < 0 else "") + "_".join([text] + groups)


# ---------------------------------------------------------------------------------------------
# Expressions: a struct literal, an array, or plain text; each renders on one line if it fits.


class Struct:
    def __init__(self, path, fields):
        self.path, self.fields = path, fields  # fields: [(name, expression)]


class Array:
    def __init__(self, items, reference=False):
        self.items = items
        self.opening = "&[" if reference else "["  # `&[...]`: a slice of a promoted array


def one_line(e):
    if isinstance(e, Struct):
        return "%s { %s }" % (e.path, ", ".join("%s: %s" % (n, one_line(v)) for n, v in e.fields))
    if isinstance(e, Array):
        return "%s%s]" % (e.opening, ", ".join(one_line(v) for v in e.items))
    return e


def fill(items, indent, width):
    """Short items joined into rows of at most `width` columns, each item followed by a comma."""
    rows, row = [], ""
    for item in (i + "," for i in items):
        if row and indent + len(row) + 1 + len(item) > width:
            rows.append(" " * indent + row)
            row = item
        else:
            row = row + " " + item if row else item
    return rows + [" " * indent + row]


def layout(e, indent, prefix, suffix):
    """Lines of `prefix` + `e` + `suffix`, at `indent` spaces."""
    pad = " " * indent
    line = pad + prefix + one_line(e) + suffix
    if len(line) <= MAX_WIDTH or not isinstance(e, (Struct, Array)):
        return [line]
    if isinstance(e, Struct):
        lines = [pad + prefix + e.path + " {"]
        for name, value in e.fields:
            lines += layout(value, indent + 4, name + ": ", ",")
        return lines + [pad + "}" + suffix]
    if all(isinstance(v, str) and len(v) <= 10 for v in e.items):
        # Short items fill each row, to one column short of the width, as rustfmt does.
        body = fill(e.items, indent + 4, MAX_WIDTH - 1)
    else:
        body = [line for item in e.items for line in layout(item, indent + 4, "", ",")]
    return [pad + prefix + e.opening] + body + [pad + "]" + suffix]


def doc_lines(text):
    """`text` as `///` lines of at most MAX_WIDTH columns."""
    lines, line = [], "///"
    for word in text.split():
        if len(line) + 1 + len(word) > MAX_WIDTH:
            lines.append(line)
            line = "///"
        line += " " + word
    return lines + [line]


def static(name, rust_type, e, public=False, doc=None):
    """A `static` item and a blank line. An array that doesn't fit after the `=` but fits on
    the next line goes there, as rustfmt puts it."""
    lines = doc_lines(doc) if doc else []
    head = "%sstatic %s: %s =" % ("pub " if public else "", name, rust_type)
    text = one_line(e)
    if isinstance(e, Array) and len(head + " " + text + ";") > MAX_WIDTH >= len("    " + text + ";"):
        return lines + [head, "    " + text + ";", ""]
    return lines + layout(e, 0, head + " ", ";") + [""]


def table_static(name, values):
    """A table's values, in plain digits (dense data)."""
    return static(name, "[u32; %d]" % len(values), Array([str(v) for v in values]))


def table(name):
    return "Table(&%s)" % name


def ints(values):
    """A short array of integers: grouped digits for up to 4 values, plain for more."""
    return Array([number(v) if len(values) <= 4 else str(v) for v in values])


def section(title):
    return ["// " + "-" * 87, "// " + title, ""]


# ---------------------------------------------------------------------------------------------
# The file.


def render(p, sha256):
    """The generated Rust source of profile `p` (a dict, as in the JSON), whose file's SHA-256
    is `sha256` (lower-case hex)."""
    out = HEADER.splitlines() + [""]
    out += ["use super::profile::{"] + fill(TYPES, 4, MAX_WIDTH) + ["};", ""]
    out += profile_static(p, sha256)

    out += section("Markets, and the distinct tier tables they use.")
    tiers = tier_tables(p["markets"])
    markets = Array([market(m, tiers) for m in p["markets"]])
    out += static("MARKETS", "[Market; %d]" % len(p["markets"]), markets)
    for n, (rows, symbols) in enumerate(tiers.values(), 1):
        rust_type = "[Tier; %d]" % len(rows)
        out += static("TIERS_%d" % n, rust_type, Array([tier(r) for r in rows]), doc=", ".join(symbols))

    out += section("Book shapes, per class.")
    for shape in p["book_shapes"]:
        out += book_shape(shape)

    out += section("Spreads: one real tick, or a split lognormal (per class, and per other macro market).")
    out += static("ONE_TICK", "Spread", "Spread::OneTick")
    for s in p["spreads"]:
        out += spread(s)

    out += section("Price moves, per max-leverage class, and jumps.")
    for m in p["moves"]:
        out += moves(m)
    out += table_static("HALF_NORMAL_MILLI", p["half_normal_milli"])
    out += table_static("JUMP_CENTIBPS", p["jumps"]["centibps"])

    out += section("Takers.")
    out += table_static("CLUSTER_SIZE_PPM", p["takers"]["cluster_size_ppm"])
    out += table_static("CLUSTER_GAP_MS", p["takers"]["cluster_gap_ms"])
    masses = [
        Struct("PointMass", [("cents", number(cents)), ("share_ppm", number(share))])
        for cents, share in p["taker_notional"]["point_masses"]
    ]
    out += static("POINT_MASSES", "[PointMass; %d]" % len(masses), Array(masses))
    out += table_static("TAKER_CONTINUOUS_CENTS", p["taker_notional"]["continuous_cents"])

    out += section("Shocks.")
    out += table_static("SHOCK_MARKETS_PPM", p["shocks"]["markets_ppm"])
    return "\n".join(out).rstrip("\n") + "\n"


def profile_static(p, sha256):
    about, constants = p["about"], p["constants"]
    j, t, n, s = p["jumps"], p["takers"], p["taker_notional"], p["shocks"]
    jumps = Struct("Jumps", [
        ("over_bps", number(j["over_bps"])),
        ("one_in_market_seconds", number(j["one_in_market_seconds"])),
        ("per_market_hour_milli", number(j["per_market_hour_milli"])),
        ("observed", number(j["observed"])),
        ("centibps", table("JUMP_CENTIBPS")),
    ])
    takers = Struct("Takers", [
        ("share_of_messages_ppm", number(t["share_of_messages_ppm"])),
        ("events_per_s_milli", number(t["events_per_s_milli"])),
        ("buy_ppm", number(t["buy_ppm"])),
        ("cluster_starts_per_s_milli", number(t["cluster_starts_per_s_milli"])),
        ("cluster_size_ppm", "&CLUSTER_SIZE_PPM"),
        ("cluster_same_market_ppm", number(t["cluster_same_market_ppm"])),
        ("cluster_same_side_ppm", number(t["cluster_same_side_ppm"])),
        ("cluster_gap_ms", table("CLUSTER_GAP_MS")),
    ])
    mixture = [Struct("LogComponent", [(k, number(v)) for k, v in c.items()]) for c in n["mixture"]]
    notional = Struct("TakerNotional", [
        ("dust_ppm", number(n["dust_ppm"])),
        ("point_masses", "&POINT_MASSES"),
        ("continuous_ppm", number(n["continuous_ppm"])),
        ("truncate_below_cents", number(n["truncate_below_cents"])),
        ("mixture", Array(mixture)),
        ("continuous_cents", table("TAKER_CONTINUOUS_CENTS")),
    ])
    shocks = Struct("Shocks", [
        ("pooled_every_s", number(s["pooled_every_s"])),
        ("calm_every_s", number(s["calm_every_s"])),
        ("markets_pareto_alpha_milli", number(s["markets_pareto_alpha_milli"])),
        ("min_markets", number(s["min_markets"])),
        ("max_markets", number(s["max_markets"])),
        ("markets_ppm", "&SHOCK_MARKETS_PPM"),
        ("move_sigmas_p50_milli", number(s["move_sigmas_p50_milli"])),
        ("move_sigmas_p90_milli", number(s["move_sigmas_p90_milli"])),
        ("move_centibps_p10_p50_p90", ints(s["move_centibps_p10_p50_p90"])),
        ("stress_move_ppm", ints(s["stress_move_ppm"])),
        ("spread_ms_p50", number(s["spread_ms_p50"])),
        ("spread_ms_p90", number(s["spread_ms_p90"])),
    ])
    profile = Struct("Profile", [
        ("name", '"%s"' % about["name"]),
        ("sample", '"%s"' % about["sample"]),
        ("sha256", '"%s"' % sha256),
        ("markets", "&MARKETS"),
        ("book_shapes", Array(["&" + ident(b["class"]) for b in p["book_shapes"]])),
        ("moves", Array(["&" + MOVES_STATIC[m["class"]] for m in p["moves"]])),
        ("half_normal_milli", table("HALF_NORMAL_MILLI")),
        ("jumps", jumps),
        ("maker_activity", Struct("MakerActivity", [(k, number(v)) for k, v in p["maker_activity"].items()])),
        ("takers", takers),
        ("taker_notional", notional),
        ("bursts_median", burst(p["bursts"]["median"])),
        ("bursts_busiest", burst(p["bursts"]["busiest"])),
        ("shocks", shocks),
        ("levels_per_side", number(constants["levels_per_side"])),
        ("mark_every_ms", number(constants["mark_every_ms"])),
        ("min_notional", number(constants["min_notional_micros"])),
        ("dust_draw_cents", ints(constants["dust_draw_cents"])),
    ])
    return static("POLYMARKET", "Profile", profile, public=True, doc=about["name"] + ".")


def burst(components):
    """Two AR(1) components; floats as Python writes them, the shortest exact form."""
    fast, slow = (
        Struct("Ar1", [("phi", repr(c["phi"])), ("innovation_sd", repr(c["innovation_sd"]))])
        for c in components
    )
    return Struct("BurstModel", [("fast", fast), ("slow", slow)])


def tier_tables(markets):
    """The distinct tier tables, in order of first use: rows -> (rows, symbols using it)."""
    tables = {}
    for m in markets:
        key = tuple(tuple(r) for r in m["tiers"])
        tables.setdefault(key, (m["tiers"], []))[1].append(m["symbol"])
    return tables


def tier(row):
    return Struct("Tier", [("lower_bound", number(row[0])), ("max_leverage", number(row[1]))])


def market(m, tiers):
    n = list(tiers).index(tuple(tuple(r) for r in m["tiers"])) + 1
    return Struct("Market", [
        ("id", str(m["id"])),
        ("symbol", '"%s"' % m["symbol"]),
        ("book", "&" + ident(m["book_class"])),
        ("moves", "&" + MOVES_STATIC[m["leverage_class"]]),
        ("price_decimals", str(m["price_decimals"])),
        ("qty_decimals", str(m["qty_decimals"])),
        ("max_leverage", str(m["max_leverage"])),
        ("tiers", "&TIERS_%d" % n),
        ("start_price", number(m["start_price_ticks"])),
        ("price_grid", number(m["price_grid_ticks"])),
        ("maker_weight_ppm", number(m["maker_weight_ppm"])),
        ("taker_weight_ppm", number(m["taker_weight_ppm"])),
        ("spread", "&" + spread_static(m["spread"])),
        ("dust_ppm", number(m["dust_ppm"])),
        ("move_rms_millibps", number(m["move_rms_millibps"])),
        ("max_notional", number(m["max_notional_micros"])),
    ])


def book_shape(b):
    """A class's `BookShape`, then its levels' sizes, then its tables: three gap tails and each
    level's background sizes."""
    name = ident(b["class"])
    tables, gaps = [], []
    for bucket, g in zip(GAP_BUCKETS, b["gaps"]):
        tail = "%s_GAPS_%s_TAIL_TICKS" % (name, bucket)
        tables += table_static(tail, g["tail_ticks"])
        gaps.append(Struct("Gaps", [
            ("one_to_ten_ppm", ints(g["one_to_ten_ppm"])),
            ("beyond_ten_ppm", number(g["beyond_ten_ppm"])),
            ("tail_mu_milli", number(g["tail_mu_milli"])),
            ("tail_sd_milli", number(g["tail_sd_milli"])),
            ("tail_ticks", table(tail)),
        ]))
    levels = []
    for k, level in enumerate(b["levels"], 1):
        background = "%s_LEVEL_%d_USD" % (name, k)
        tables += table_static(background, level["background_usd"])
        levels.append(Struct("LevelSizes", [
            ("dust_ppm", number(level["dust_ppm"])),
            ("clips_ppm", Array([number(c) for c in level["clips_ppm"]], reference=True)),
            ("background_usd", table(background)),
        ]))
    shape = Struct("BookShape", [
        ("class", "BookClass::" + BOOK_CLASS[b["class"]]),
        ("spread", "&" + spread_static(b["spread"])),
        ("gaps", Array(gaps)),
        ("dust_ppm", number(b["dust_ppm"])),
        ("clips_usd", Array([number(usd) for usd in b["clips_usd"]], reference=True)),
        ("clip_jitter_ppm", number(b["clip_jitter_ppm"])),
        ("levels", "&%s_LEVELS" % name),
    ])
    levels = static("%s_LEVELS" % name, "[LevelSizes; %d]" % len(levels), Array(levels))
    return static(name, "BookShape", shape) + levels + tables


def spread(s):
    """A split-lognormal `Spread`, then its table."""
    name = spread_static(s["name"])
    model = Struct("Spread::SplitLognormal", [
        ("median_centibps", number(s["median_centibps"])),
        ("sigma_below_milli", number(s["sigma_below_milli"])),
        ("sigma_above_milli", number(s["sigma_above_milli"])),
        ("centibps", table(name + "_CENTIBPS")),
    ])
    return static(name, "Spread", model) + table_static(name + "_CENTIBPS", s["centibps"])


def moves(m):
    model = Struct("MoveModel", [
        ("class", "LeverageClass::" + LEVERAGE_CLASS[m["class"]]),
        ("no_move_ppm", number(m["no_move_ppm"])),
        ("weights_ppm", ints(m["weights_ppm"])),
        ("sd_milli", ints(m["sd_milli"])),
    ])
    return static(MOVES_STATIC[m["class"]], "MoveModel", model)
