//! # loadgen
//!
//! Deterministic synthetic order flow for the tests and benchmarks, and (Milestone 3) the
//! open-loop load for the whole pipeline. Two presets, around a fixed mid price, feed the
//! book benchmarks:
//! - [`FlowConfig::default()`], the **Milestone 0 flow**: places and cancels at prices
//!   uniform around mid, so about half of the orders trade on arrival and the book stays
//!   shallow (a few hundred resting orders). It is the stream the M0 baseline was measured
//!   on, and it must never change: a test pins it.
//! - [`FlowConfig::deep()`], the **Milestone 1 deep-book flow**: about 10,000 live orders
//!   from 1,000 accounts, dense near the top of the book and thinning out away from it,
//!   with IOC takers, post-only quotes, cancels and modifies.
//!
//! **Contract.** The same seed and config always produce exactly the same commands, on
//! every machine. That's what makes benchmark runs repeatable and lets a failing run be
//! replayed. Every option added after M0 is off by default and, while off, draws no random
//! numbers, so it can't shift the default stream.
//!
//! **Open loop.** The generator never looks at the book, like a client that doesn't wait
//! for replies. It remembers the orders it placed, not whether they filled, so some of its
//! cancels and modifies hit orders that have already gone. The book rejects those, as it
//! would real flow, and the benchmarks report the rejects.
//!
//! **Milestone 3** (`docs/PIPELINE.md` section 14; `docs/DECISIONS.md` D-027): the load
//! for the whole pipeline, in its own modules. These two flows stay exactly as they were.
//! - [`market_flow`]: the M3 synthetic flow: 67 markets, each with its own fair-value path,
//!   market makers, takers, high-leverage accounts, a thin long-lived layer, and the setup
//!   phases that go through the journal before the timed flow (14.1 to 14.7). And the
//!   Polymarket-shaped flow (D-034): [`market_flow::polymarket`], Polymarket Perps' 88 real
//!   markets traded with the shape of their recorded traffic, into the same kind of plan; its
//!   calibrated profile, [`market_flow::profile`], generated by `tools/calibrate`.
//! - [`keys`]: each account's secp256k1 key, derived from the seed, and `keys.txt` (14.8).
//! - [`presign`]: every client message signed before the run, in parallel, into an arena,
//!   in our nonce scheme or in Polymarket Perps' EIP-712 scheme (5.8); the compact unsigned
//!   arena for pre-verified runs; `presigned.bin` (14.8).
//! - [`schedule`]: when each item is sent: Poisson (or, for debugging, evenly spaced)
//!   arrivals at the offered rate (14.9), or, with `--bursts` (D-034), a Poisson process
//!   whose rate swings each second as Polymarket's recorded message rate did.
//! - [`sender`]: the open-loop sender thread, which never waits for the system: a full
//!   ring drops the message and counts it (14.10).
//!
//! Randomness comes from [`SplitMix64`], written here rather than taken from a crate: it is
//! a dozen lines, fast, and its output is fixed forever, whereas a library's could change
//! between versions (`docs/DECISIONS.md` D-006). There are no floats in what any flow
//! contains, since float functions such as `ln` can round differently on different
//! machines. The only floats are in [`schedule`]: a Poisson gap is `−ln(1 − u) / R`, and
//! bursts multiply the rate by `exp` of normal draws. They can only change *when* a message is
//! sent, never what it says (PIPELINE.md 14.9).

pub mod keys;
pub mod market_flow;
pub mod presign;
pub mod schedule;
pub mod sender;

use engine::command::{CancelOrder, Command, ModifyOrder, PlaceOrder};
use engine::types::{AccountId, MarketId, OrderId, Price, Qty, Side, TimeInForce, order_id};

/// SplitMix64: a tiny, well-known pseudo-random generator (Steele, Lea and Flood, 2014).
/// Good statistical quality for simulation; not for cryptography.
#[derive(Clone, Debug)]
pub struct SplitMix64 {
    state: u64,
}

impl SplitMix64 {
    pub fn new(seed: u64) -> Self {
        SplitMix64 { state: seed }
    }

    pub fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    /// A value in `0..n`. The tiny modulo bias is irrelevant for load generation.
    pub fn below(&mut self, n: u64) -> u64 {
        self.next_u64() % n
    }

    /// A value in `lo..=hi`.
    pub fn in_range(&mut self, lo: i64, hi: i64) -> i64 {
        lo + self.below((hi - lo + 1) as u64) as i64
    }

    /// True with probability `percent / 100`.
    pub fn chance(&mut self, percent: u64) -> bool {
        self.below(100) < percent
    }
}

/// How order prices are spread around mid.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Prices {
    /// Uniform in `mid - half_width ..= mid + half_width`, whatever the side, so about half
    /// of the orders cross the spread and trade on arrival. The M0 flow.
    Uniform,
    /// Resting orders sit on their own side of mid, bids at `mid - d` and asks at `mid + d`,
    /// with the distance `d` skewed towards 0: starting from 0, each further tick is taken
    /// with probability `further_tick_percent` / 100, up to `half_width` (a geometric
    /// distribution, mean `p / (1 - p)` ticks). So the book is dense near the top and thins
    /// out further away.
    ///
    /// At `d = 0` bids and asks meet: a quote at mid trades if the other side holds the mid,
    /// or is rejected if it is post-only. An IOC taker gets a distance drawn the same way
    /// but on the other side of mid, so it crosses the spread and takes what rests up to
    /// its price, usually the first level or two.
    Skewed { further_tick_percent: u64 },
}

/// Shape of the flow. `Default` is the M0 flow; [`FlowConfig::deep`] the deep-book flow.
#[derive(Clone, Copy, Debug)]
pub struct FlowConfig {
    pub seed: u64,
    pub market: MarketId,
    /// Accounts are numbered `1..=accounts`.
    pub accounts: AccountId,
    pub mid: Price,
    /// No order is priced further than this from `mid`. With the default
    /// [`Prices::Uniform`], prices are uniform in `mid - half_width ..= mid + half_width`,
    /// so roughly half of the orders cross the spread and trade.
    pub half_width: Price,
    /// Every order's size is uniform in `1..=max_qty` lots.
    pub max_qty: Qty,
    /// Share of commands that cancel a random earlier order instead of placing a new one.
    pub cancel_percent: u64,

    // Added in Milestone 1. Each default turns the option off, which keeps the M0 stream.
    /// How prices are spread around `mid`. Default: [`Prices::Uniform`].
    pub prices: Prices,
    /// Share of the remaining commands (those that aren't random cancels) that modify a
    /// random earlier order. Default 0.
    pub modify_percent: u64,
    /// The most orders the generator keeps live, as far as it knows. At this many, a
    /// command that would have been a place cancels a random live order instead, the way
    /// a market maker keeps a fixed number of quotes out. The book then settles at a
    /// steady depth rather than growing. Default `usize::MAX`: no cap.
    pub max_live_orders: usize,
    /// Share of places that are IOC takers. Default 0: every order is GTC.
    pub ioc_percent: u64,
    /// Share of the other places (the GTC ones) that are post-only. Default 0.
    pub post_only_percent: u64,
}

impl Default for FlowConfig {
    fn default() -> Self {
        FlowConfig {
            seed: 1,
            market: 1,
            accounts: 100,
            mid: 10_000,
            half_width: 20,
            max_qty: 10,
            cancel_percent: 40,
            prices: Prices::Uniform,
            modify_percent: 0,
            max_live_orders: usize::MAX,
            ioc_percent: 0,
            post_only_percent: 0,
        }
    }
}

impl FlowConfig {
    /// The deep-book flow (Milestone 1): a book with thousands of resting orders, where a
    /// linear scan gets slow and the fast book has to show it doesn't.
    ///
    /// These are **assumed parameters** (INFO.md section 7), chosen to be plausible, not
    /// calibrated against real data (that is "Later", INFO.md section 12.4):
    /// - **1,000 accounts, about 10 orders live each** (`max_live_orders` 10,000). Once the
    ///   generator has 10,000 orders out, each new one replaces a random old one. So cancels
    ///   come at random ages rather than at a fixed lifetime, and in steady state there are
    ///   as many cancels as resting places: a cancel-heavy flow, as on real venues. There
    ///   are no other cancels (`cancel_percent` 0).
    /// - **Distance from mid**: 95% chance of each further tick. The mean distance is 19
    ///   ticks; about 5% of quotes land on each of the first few levels, and 0.6% in all
    ///   beyond 100 ticks. The 250-tick limit is practically never reached, so no orders
    ///   pile up at it.
    /// - **10% modifies**: half move the order to a new distance from mid, half set a new
    ///   total size.
    /// - **5% of places are IOC takers** (about 2% of commands), so there is a fill for
    ///   about one command in 20: real venues see many orders per trade. Each fill leaves
    ///   the generator an order it will later cancel or modify in vain, so the taker share
    ///   sets the reject share: about 5% of commands (7% with 10% takers).
    /// - **20% of resting places are post-only**, as market makers use them.
    /// - **Sizes 1-10 lots** for every order, as in the M0 flow, and the same fixed mid of
    ///   10,000 ticks, so both flows fit the same book configuration. A moving fair value
    ///   is Milestone 3.
    ///
    /// The generator reaches its 10,000 live orders after about 12,000 commands. After
    /// that, the mix is about 46% places, 44% cancels and 10% modifies. Orders that filled
    /// without the generator knowing stay on its list until it happens to cancel them, so
    /// the book itself holds fewer: about 9,100 orders on 110-130 levels per side after
    /// 100,000 commands, and about the same from then on.
    pub fn deep() -> Self {
        FlowConfig {
            seed: 1,
            market: 1,
            accounts: 1_000,
            mid: 10_000,
            half_width: 250,
            max_qty: 10,
            cancel_percent: 0,
            prices: Prices::Skewed { further_tick_percent: 95 },
            modify_percent: 10,
            max_live_orders: 10_000,
            ioc_percent: 5,
            post_only_percent: 20,
        }
    }
}

/// An order the generator has placed and not cancelled, as the client last sent it. It
/// may have filled since: the generator never sees the book.
#[derive(Clone, Copy, Debug)]
struct LiveOrder {
    order_id: OrderId,
    side: Side,
    price: Price,
    /// The order's total size as the client last set it (by the place or a modify). Fills
    /// don't reduce it, since the client doesn't see them.
    size: Qty,
}

/// An endless, deterministic stream of place, cancel and modify commands. Each command is
/// chosen in this order (see [`FlowConfig`] for each option):
/// 1. With no live orders, place one.
/// 2. With probability `cancel_percent`, cancel a random live order.
/// 3. Otherwise, with probability `modify_percent`, modify a random live order.
/// 4. Otherwise, at `max_live_orders`, cancel a random live order to make room.
/// 5. Otherwise, place an order.
///
/// It is open-loop (module docs): some cancels and modifies target orders that have
/// already filled, and the book rejects those as `UnknownOrder`, as real flow would.
#[derive(Clone, Debug)]
pub struct SyntheticFlow {
    config: FlowConfig,
    rng: SplitMix64,
    /// Next sequence number per account (index 0 unused).
    next_seq: Vec<u32>,
    /// GTC orders placed and not yet cancelled by this generator.
    live: Vec<LiveOrder>,
}

impl SyntheticFlow {
    pub fn new(config: FlowConfig) -> Self {
        SyntheticFlow {
            config,
            rng: SplitMix64::new(config.seed),
            next_seq: vec![0; config.accounts as usize + 1],
            live: Vec::new(),
        }
    }

    /// True with probability `percent / 100`, like [`SplitMix64::chance`], except that 0%
    /// draws no random number at all. That is how an option switched off leaves the M0
    /// stream exactly as it was.
    fn roll(&mut self, percent: u64) -> bool {
        percent > 0 && self.rng.chance(percent)
    }

    /// How far from mid to price an order, drawn before its side is known (see
    /// [`SyntheticFlow::price_at`]):
    /// - [`Prices::Uniform`]: a signed offset in `-half_width..=half_width`.
    /// - [`Prices::Skewed`]: a distance in `0..=half_width`, from 0 up, one tick at a time.
    fn draw_offset(&mut self) -> Price {
        let half_width = self.config.half_width;
        match self.config.prices {
            Prices::Uniform => self.rng.in_range(-half_width, half_width),
            Prices::Skewed { further_tick_percent } => {
                let mut distance = 0;
                while distance < half_width && self.rng.chance(further_tick_percent) {
                    distance += 1;
                }
                distance
            }
        }
    }

    /// The price of an order on `side` at `offset` from mid (from `draw_offset`). With
    /// skewed prices, a resting order goes on its own side of mid and a taker on the other.
    fn price_at(&self, side: Side, offset: Price, taker: bool) -> Price {
        let mid = self.config.mid;
        match self.config.prices {
            Prices::Uniform => mid + offset,
            Prices::Skewed { .. } => match (side, taker) {
                // A resting bid, or a sell that crosses down into the bids.
                (Side::Buy, false) | (Side::Sell, true) => mid - offset,
                // A resting ask, or a buy that crosses up into the asks.
                (Side::Sell, false) | (Side::Buy, true) => mid + offset,
            },
        }
    }

    fn next_place(&mut self) -> Command {
        let c = self.config;
        // Account, offset, size and side are the M0 flow's draws, in its order. The options
        // after them draw nothing while off (`roll`), so the default stream is unchanged.
        let account = 1 + self.rng.below(c.accounts as u64) as AccountId;
        self.next_seq[account as usize] += 1;
        let id = order_id(account, self.next_seq[account as usize]);
        let offset = self.draw_offset();
        let qty = self.rng.in_range(1, c.max_qty);
        let side = if self.rng.chance(50) { Side::Buy } else { Side::Sell };
        let taker = self.roll(c.ioc_percent);
        let post_only = !taker && self.roll(c.post_only_percent);

        let price = self.price_at(side, offset, taker);
        // Only a GTC order can rest, so only it can be cancelled or modified later.
        if !taker {
            self.live.push(LiveOrder { order_id: id, side, price, size: qty });
        }
        Command::PlaceOrder(PlaceOrder {
            order_id: id,
            price,
            qty,
            market: c.market,
            side,
            tif: if taker { TimeInForce::Ioc } else { TimeInForce::Gtc },
            post_only,
        })
    }

    fn next_cancel(&mut self) -> Command {
        let i = self.rng.below(self.live.len() as u64) as usize;
        let order = self.live.swap_remove(i);
        Command::CancelOrder(CancelOrder { order_id: order.order_id, market: self.config.market })
    }

    /// Modifies a random live order. Half the time it moves to a new price (a fresh offset
    /// from mid, on its own side) and keeps its total size; otherwise it keeps its price and
    /// gets a new total size.
    ///
    /// Either way, `new_size` is the order's *total* size as the client wants it, never
    /// reduced by fills the client hasn't seen. The book subtracts what has filled
    /// (`command::ModifyOrder`), and removes the order if nothing would be left.
    fn next_modify(&mut self) -> Command {
        let c = self.config;
        let i = self.rng.below(self.live.len() as u64) as usize;
        let mut order = self.live[i];
        if self.rng.chance(50) {
            let offset = self.draw_offset();
            order.price = self.price_at(order.side, offset, false);
        } else {
            order.size = self.rng.in_range(1, c.max_qty);
        }
        self.live[i] = order;
        Command::ModifyOrder(ModifyOrder {
            order_id: order.order_id,
            new_price: order.price,
            new_size: order.size,
            market: c.market,
        })
    }
}

impl Iterator for SyntheticFlow {
    type Item = Command;

    fn next(&mut self) -> Option<Command> {
        let c = self.config;
        let command = if self.live.is_empty() {
            self.next_place()
        } else if self.roll(c.cancel_percent) {
            self.next_cancel()
        } else if self.roll(c.modify_percent) {
            self.next_modify()
        } else if self.live.len() >= c.max_live_orders {
            // At the cap: make room instead of placing.
            self.next_cancel()
        } else {
            self.next_place()
        };
        Some(command)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use engine::book::{Book, BookConfig, OrderBook, RestingOrder};
    use engine::event::Event;
    use std::collections::HashMap;

    #[test]
    fn splitmix64_matches_the_published_reference_values() {
        // First outputs for seed 1234567, from the reference C implementation.
        let mut rng = SplitMix64::new(1234567);
        assert_eq!(rng.next_u64(), 6457827717110365317);
        assert_eq!(rng.next_u64(), 3203168211198807973);
    }

    #[test]
    fn the_same_seed_gives_the_same_flow() {
        let a: Vec<Command> = SyntheticFlow::new(FlowConfig::default()).take(1_000).collect();
        let b: Vec<Command> = SyntheticFlow::new(FlowConfig::default()).take(1_000).collect();
        assert_eq!(a, b);
        let other: Vec<Command> =
            SyntheticFlow::new(FlowConfig { seed: 2, ..FlowConfig::default() }).take(1_000).collect();
        assert_ne!(a, other);
    }

    #[test]
    fn the_flow_mixes_places_and_cancels_within_the_configured_band() {
        let config = FlowConfig::default();
        let commands: Vec<Command> = SyntheticFlow::new(config).take(10_000).collect();
        let places = commands.iter().filter(|c| matches!(c, Command::PlaceOrder(_))).count();
        assert!((5_000..8_000).contains(&places), "places = {places}");
        for c in &commands {
            if let Command::PlaceOrder(p) = c {
                assert!((config.mid - config.half_width..=config.mid + config.half_width).contains(&p.price));
                assert!((1..=config.max_qty).contains(&p.qty));
            }
        }
    }

    fn gtc_place(account: AccountId, seq: u32, price: Price, qty: Qty) -> Command {
        Command::PlaceOrder(PlaceOrder {
            order_id: order_id(account, seq),
            price,
            qty,
            market: 1,
            side: Side::Buy,
            tif: TimeInForce::Gtc,
            post_only: false,
        })
    }

    #[test]
    fn the_default_flow_is_still_the_m0_flow() {
        // The M0 baseline in docs/BENCHMARKS.md was measured on exactly this stream. These
        // values were taken from the M0 generator. One extra random draw anywhere would
        // shift everything after it, including the last command.
        let commands: Vec<Command> = SyntheticFlow::new(FlowConfig::default()).take(10_000).collect();
        assert_eq!(commands[0], gtc_place(66, 1, 9_992, 1));
        assert_eq!(commands[1], gtc_place(49, 1, 9_986, 4));
        assert_eq!(commands[2], gtc_place(38, 1, 10_001, 5));
        assert_eq!(commands[9_999], gtc_place(7, 55, 9_983, 7));
        let cancels = commands.iter().filter(|c| matches!(c, Command::CancelOrder(_))).count();
        assert_eq!(cancels, 4_014);
    }

    #[test]
    fn the_deep_flow_is_the_same_for_the_same_seed() {
        let a: Vec<Command> = SyntheticFlow::new(FlowConfig::deep()).take(20_000).collect();
        let b: Vec<Command> = SyntheticFlow::new(FlowConfig::deep()).take(20_000).collect();
        assert_eq!(a, b);
        let other: Vec<Command> =
            SyntheticFlow::new(FlowConfig { seed: 2, ..FlowConfig::deep() }).take(20_000).collect();
        assert_ne!(a, other);
    }

    /// `part` as a percentage of `whole`.
    fn percent(part: usize, whole: usize) -> f64 {
        100.0 * part as f64 / whole as f64
    }

    #[test]
    fn the_deep_flow_mixes_commands_in_the_documented_proportions() {
        // Skip the first 20,000 commands: the generator reaches its cap of live orders after
        // about 12,000, and only then does it start cancelling.
        let config = FlowConfig::deep();
        let mut flow = SyntheticFlow::new(config);
        let steady: Vec<Command> = flow.by_ref().skip(20_000).take(50_000).collect();
        assert!(flow.live.len() <= config.max_live_orders);

        let mut places = 0;
        let mut iocs = 0;
        let mut gtcs: usize = 0;
        let mut post_only = 0;
        let mut cancels = 0;
        let mut modifies = 0;
        for command in &steady {
            match command {
                Command::PlaceOrder(p) if p.tif == TimeInForce::Ioc => {
                    places += 1;
                    iocs += 1;
                    assert!(!p.post_only, "an IOC taker is never post-only");
                }
                Command::PlaceOrder(p) => {
                    places += 1;
                    gtcs += 1;
                    post_only += usize::from(p.post_only);
                }
                Command::CancelOrder(_) => cancels += 1,
                Command::ModifyOrder(_) => modifies += 1,
                other => panic!("unexpected command {other:?}"),
            }
        }
        let n = steady.len();
        // Expected (FlowConfig::deep docs): 10% modifies; the other 90% split so that
        // cancels equal GTC places, which are 95% of places: 46.2% places, 43.8% cancels.
        let near = |actual: f64, expected: f64| (actual - expected).abs() < 1.5;
        assert!(near(percent(modifies, n), 10.0), "modifies {:.1}%", percent(modifies, n));
        assert!(near(percent(places, n), 46.2), "places {:.1}%", percent(places, n));
        assert!(near(percent(cancels, n), 43.8), "cancels {:.1}%", percent(cancels, n));
        assert!(gtcs.abs_diff(cancels) <= 1, "at the cap, every resting place replaces an order");
        assert!(near(percent(iocs, places), 5.0), "IOC {:.1}% of places", percent(iocs, places));
        assert!(near(percent(post_only, gtcs), 20.0), "post-only {:.1}% of GTC", percent(post_only, gtcs));
    }

    #[test]
    fn deep_quotes_rest_on_their_own_side_mostly_near_mid_and_takers_cross() {
        let config = FlowConfig::deep();
        let (mut near_mid, mut far_out) = (0, 0);
        for command in SyntheticFlow::new(config).take(50_000) {
            let Command::PlaceOrder(p) = command else { continue };
            let distance = (p.price - config.mid).abs();
            assert!(distance <= config.half_width);
            assert!((1..=config.max_qty).contains(&p.qty));
            // Resting bids at or below mid, resting asks at or above; takers the other way.
            let below_mid = p.price <= config.mid;
            let above_mid = p.price >= config.mid;
            match (p.side, p.tif) {
                (Side::Buy, TimeInForce::Gtc) | (Side::Sell, TimeInForce::Ioc) => assert!(below_mid, "{p:?}"),
                (Side::Sell, TimeInForce::Gtc) | (Side::Buy, TimeInForce::Ioc) => assert!(above_mid, "{p:?}"),
            }
            if distance <= 10 {
                near_mid += 1;
            } else if distance > 50 {
                far_out += 1;
            }
        }
        // Geometric at 95% per tick: 43% of orders within 10 ticks, 7% beyond 50.
        assert!(near_mid > 4 * far_out, "{near_mid} within 10 ticks, {far_out} beyond 50");
    }

    #[test]
    fn deep_modifies_send_the_orders_total_size_as_the_client_last_set_it() {
        // Follow each order's total size from its place through its modifies. A modify
        // that moves the price repeats that total: it is not reduced by fills the client
        // can't see. One that keeps the price sets a new total.
        let config = FlowConfig::deep();
        let mut last_sent: HashMap<OrderId, (Price, Qty)> = HashMap::new();
        let (mut repriced, mut resized) = (0, 0);
        for command in SyntheticFlow::new(config).take(50_000) {
            match command {
                Command::PlaceOrder(p) if p.tif == TimeInForce::Gtc => {
                    last_sent.insert(p.order_id, (p.price, p.qty));
                }
                Command::PlaceOrder(_) => {}
                Command::CancelOrder(c) => {
                    last_sent.remove(&c.order_id).expect("cancels only orders it placed");
                }
                Command::ModifyOrder(m) => {
                    let (price, size) = last_sent[&m.order_id];
                    if m.new_price != price {
                        assert_eq!(m.new_size, size, "a price move keeps the total size");
                        repriced += 1;
                    } else {
                        assert!((1..=config.max_qty).contains(&m.new_size));
                        resized += 1;
                    }
                    last_sent.insert(m.order_id, (m.new_price, m.new_size));
                }
                other => panic!("unexpected command {other:?}"),
            }
        }
        assert!(repriced > 1_000 && resized > 1_000, "{repriced} price moves, {resized} resizes");
    }

    #[test]
    fn the_deep_flow_keeps_thousands_of_orders_resting_on_many_levels() {
        let config = FlowConfig::deep();
        let mut book =
            Book::new(BookConfig { market: config.market, min_price: 1, max_price: 2 * config.mid });
        let mut events: Vec<Event> = Vec::new();
        for command in SyntheticFlow::new(config).take(60_000) {
            match command {
                Command::PlaceOrder(p) => book.place(&p, &mut events),
                Command::CancelOrder(c) => book.cancel(c.order_id, &mut events),
                Command::ModifyOrder(m) => book.modify(m.order_id, m.new_price, m.new_size, &mut events),
                other => panic!("unexpected command {other:?}"),
            }
            events.clear();
        }
        let snapshot = book.snapshot();
        let resting = snapshot.bids.len() + snapshot.asks.len();
        assert!((5_000..=20_000).contains(&resting), "{resting} resting orders");
        for side in [&snapshot.bids, &snapshot.asks] {
            let per_level = orders_per_level(side);
            assert!(per_level.len() >= 50, "only {} levels on one side", per_level.len());
            // Dense near the top: the best 10 levels hold more orders than all the levels
            // beyond the 50th.
            let top: usize = per_level[..10].iter().sum();
            let tail: usize = per_level[50..].iter().sum();
            assert!(top > tail, "{top} orders on the best 10 levels, {tail} beyond the 50th");
        }
    }

    /// The number of orders on each level of one side of a snapshot, best level first. The
    /// snapshot lists orders best price first, so each level's orders are adjacent.
    fn orders_per_level(side: &[RestingOrder]) -> Vec<usize> {
        let mut counts = Vec::new();
        let mut last_price = None;
        for order in side {
            if last_price == Some(order.price) {
                *counts.last_mut().expect("a level was started") += 1;
            } else {
                counts.push(1);
                last_price = Some(order.price);
            }
        }
        counts
    }
}
